version: '3.1'

# note: the newer mysql client version doesn't support
#       mysql_native_password authentication by default
#
#       simplest workaround on mac might be:
#            brew install mysql-client@8.4
#            brew unlink mysql
#            brew link mysql-client@8.4
#            (cf. https://github.com/Homebrew/homebrew-core/issues/180498#issuecomment-2293057321)

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root-secret
      MARIADB_DATABASE: nutrition
      MARIADB_USER: nutrition-admin
      MARIADB_PASSWORD: nutrition-secret
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
