# Generated by Django 5.1 on 2024-09-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
