# Generated by Django 5.1 on 2024-09-02 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_portion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.meal'),
        ),
    ]
